### ISSUE TITLE
Build fails on musl

### ISSUE THREAD

**Issue by katp32** [rhboot/efivar#226]
Before you close this issue claiming that it's been fixed by recent commits, no. It hasn't.

The code still uses qsort_r(), which is not supported by musl, causing the build to fail. This is still an issue. I'm curious as to how the build was tested before in a way that gave the impression that it no longer failed.

**Comment by frozencemetery** [comment]
The hostility isn't welcome.

musl is not something we the maintainers support (for reasons that, in order to keep this conversation civil, I won't go into).  *Patches are generally accepted*, but it's not something we're testing.  You're free to read other issues to see *why* they've been closed, but in #224 and #206 we received confirmation that things were working.  If they're not, then it's news to us.

**Comment by floppym** [comment]
Support for `qsort_r` was added in [musl-1.2.3](https://git.musl-libc.org/cgit/musl/tree/WHATSNEW?h=v1.2.3#n2296).
